### ISSUE TITLE
Installing with NPM fails on Mac OSX

### ISSUE THREAD

**Issue by ambodi** [Project-OSRM/node-osrm#238] opened 2016-09-06 14:24 UTC
$ npm install osrm results is like this (NODE V 6.3.1):

```
> osrm@5.3.3 install /Users/ara/dev/iteam/tsab-estimate/node_modules/osrm
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.3.3/Release/node-v48-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for osrm@5.3.3 and node@6.3.1 (node-v48 ABI) (falling back to source compile with node-gyp)
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
/bin/sh: pkg-config: command not found
gyp: Call to 'pkg-config libosrm --libs --static' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/ara/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/Users/ara/.nvm/versions/node/v6.3.1/bin/node" "/Users/ara/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/ara/dev/iteam/tsab-estimate/node_modules/osrm/lib/binding/osrm.node" "--module_name=osrm" "--module_path=/Users/ara/dev/iteam/tsab-estimate/node_modules/osrm/lib/binding"
gyp ERR! cwd /Users/ara/dev/iteam/tsab-estimate/node_modules/osrm
gyp ERR! node -v v6.3.1
gyp ERR! node-gyp -v v3.3.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/ara/.nvm/versions/node/v6.3.1/bin/node /Users/ara/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/ara/dev/iteam/tsab-estimate/node_modules/osrm/lib/binding/osrm.node --module_name=osrm --module_path=/Users/ara/dev/iteam/tsab-estimate/node_modules/osrm/lib/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/ara/dev/iteam/tsab-estimate/node_modules/osrm/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:852:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
node-pre-gyp ERR! System Darwin 15.6.0
node-pre-gyp ERR! command "/Users/ara/.nvm/versions/node/v6.3.1/bin/node" "/Users/ara/dev/iteam/tsab-estimate/node_modules/osrm/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/ara/dev/iteam/tsab-estimate/node_modules/osrm
node-pre-gyp ERR! node -v v6.3.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.29
node-pre-gyp ERR! not ok
Failed to execute '/Users/ara/.nvm/versions/node/v6.3.1/bin/node /Users/ara/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/ara/dev/iteam/tsab-estimate/node_modules/osrm/lib/binding/osrm.node --module_name=osrm --module_path=/Users/ara/dev/iteam/tsab-estimate/node_modules/osrm/lib/binding' (1)
npm WARN gmaps-routing@1.0.0 No repository field.
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/ara/.nvm/versions/node/v6.3.1/bin/node" "/Users/ara/.nvm/versions/node/v6.3.1/bin/npm" "install" "osrm"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! osrm@5.3.3 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the osrm@5.3.3 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the osrm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs osrm
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls osrm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ara/dev/iteam/tsab-estimate/npm-debug.log
```

**Comment by daniel-j-h** [comment] 2016-09-06 15:00
Duplicate of https://github.com/Project-OSRM/node-osrm/issues/226.

**Closed by daniel-j-h** 2016-09-06 15:00 UTC

**Comment by ambodi** [comment] 2016-09-07 10:48
@daniel-j-h but it's only when you install. It will continues working if you install it with other nodes and then change back to v6.3.0!

**Comment by daniel-j-h** [comment] 2016-09-07 10:58
Yes, we don't publish binaries for other versions than v4 at the moment.

> node-pre-gyp ERR! Pre-built binaries not found for osrm@5.3.3 and node@6.3.1 (node-v48 ABI) (falling back to source compile with node-gyp)

cc @springmeyer to keep you in the loop about v4 / v6

**Comment by springmeyer** [comment] 2016-09-07 21:10
> @daniel-j-h but it's only when you install. It will continues working if you install it with other nodes and then change back to v6.3.0!

@ambodi - no. You cannot change between major version of node without re-installing. That will not predictably work so I don't recommend trying it.

> cc @springmeyer to keep you in the loop about v4 / v6

@daniel-j-h thank you. Yes, we can consider adding precompiled binaries for v6 in the future. Let's discuss when to move to v6 at #239
